import { test, expect } from "@playwright/test";
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// All test data is synthetic. The fixture is generated by
// tests/fixtures/build_sample.py and contains a small representative tree
// (PNG, SVG, XML, plain text, raw binary) under nested folders. The
// matching counts and structure below must stay in sync with that script.
const FIXTURE = resolve(__dirname, "fixtures", "sample.skin");
const BUILDER = resolve(__dirname, "fixtures", "build_sample.py");
const FIXTURE_FILE_COUNT = 5;
const FIXTURE_NAME = "sample.skin";

test.beforeAll(() => {
  // Regenerate on every run so changes to the builder script are picked up
  // automatically and so a fresh checkout works without manual steps.
  execFileSync("python3", [BUILDER, FIXTURE], { stdio: "inherit" });
  if (!existsSync(FIXTURE)) {
    throw new Error(`Sample fixture missing after build: ${FIXTURE}`);
  }
});

test("app boots without console errors", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push("pageerror: " + String(e)));
  page.on("console", (msg) => {
    if (msg.type() === "error") errors.push(msg.text());
  });

  await page.goto("/");
  await expect(page.getByRole("heading", { name: "PreSonus .skin file viewer" })).toBeVisible();
  await expect(page.getByText("Drop a")).toBeVisible();
  expect(errors).toEqual([]);
});

test(`loads ${FIXTURE_NAME} and shows ${FIXTURE_FILE_COUNT} files`, async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(String(e)));
  page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });

  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles(FIXTURE);

  const info = page.locator("header .info");
  await expect(info).toContainText(FIXTURE_NAME);
  await expect(info).toContainText("format v1");
  await expect(info).toContainText(`${FIXTURE_FILE_COUNT} file`);

  // Tree pane renders the synthetic top-level folders.
  await expect(page.locator(".tree-pane")).toBeVisible();
  await expect(page.locator(".tree-pane").getByText("images")).toBeVisible();
  await expect(page.locator(".tree-pane").getByText("meta")).toBeVisible();

  // Open every still-closed folder so all file rows become visible.
  for (let step = 0; step < 10; step++) {
    const closed = page.locator(
      '.tree-pane [role="treeitem"][aria-expanded="false"]',
    );
    const n = await closed.count();
    if (n === 0) break;
    for (let i = 0; i < n; i++) await closed.nth(i).click();
  }
  // Confirm every fixture file shows up in the tree.
  for (const name of [
    "pixel.png",
    "square.svg",
    "theme.xml",
    "README.txt",
    "bytes.bin",
  ]) {
    await expect(page.locator(".tree-pane").getByText(name)).toBeVisible();
  }

  expect(errors).toEqual([]);
});

test("PNG file decompresses and renders as an image", async ({ page }) => {
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles(FIXTURE);
  await page.locator(".tree-pane").getByText("pixel.png").click();

  const preview = page.locator(".preview-pane");
  await expect(preview.locator(".err")).toHaveCount(0);
  await expect(preview.locator(".placeholder")).toHaveCount(0);
  const img = preview.locator("img");
  await expect(img).toBeVisible();
  await expect(img).toHaveAttribute("src", /^blob:/);
});

test("XML file decompresses and renders as text", async ({ page }) => {
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles(FIXTURE);
  await page.locator(".tree-pane").getByText("theme.xml").click();

  const preview = page.locator(".preview-pane");
  await expect(preview.locator(".err")).toHaveCount(0);
  const pre = preview.locator("pre");
  await expect(pre).toBeVisible();
  await expect(pre).toContainText("<theme");
  await expect(pre).toContainText("sample");
});

test("binary file falls back to a hex dump", async ({ page }) => {
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles(FIXTURE);

  // bytes.bin lives in meta/raw - open that nested folder first.
  for (let step = 0; step < 5; step++) {
    const closed = page.locator(
      '.tree-pane [role="treeitem"][aria-expanded="false"]',
    );
    const n = await closed.count();
    if (n === 0) break;
    for (let i = 0; i < n; i++) await closed.nth(i).click();
  }
  await page.locator(".tree-pane").getByText("bytes.bin").click();

  const pre = page.locator(".preview-pane pre.hex");
  await expect(pre).toBeVisible();
  // build_sample.py writes bytes 0x00..0xff into bytes.bin, so a hex dump
  // line containing the printable ASCII run should appear.
  await expect(pre).toContainText("41 42 43 44 45 46 47");
});

test("selecting a file shows a preview and lets us download it", async ({ page }) => {
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles(FIXTURE);

  await page.locator(".tree-pane").getByText("pixel.png").click();
  const preview = page.locator(".preview-pane");
  const downloadBtn = preview.getByRole("button", { name: /download/i });
  await expect(downloadBtn).toBeVisible();

  const [download] = await Promise.all([
    page.waitForEvent("download"),
    downloadBtn.click(),
  ]);
  expect(download.suggestedFilename()).toBe("pixel.png");
  const stream = await download.createReadStream();
  const chunks: Buffer[] = [];
  for await (const c of stream) chunks.push(c as Buffer);
  const buf = Buffer.concat(chunks);
  // PNG magic.
  expect(buf.slice(0, 8).toString("hex")).toBe("89504e470d0a1a0a");
});

test("download-all-as-zip produces a valid zip", async ({ page }) => {
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles(FIXTURE);
  await expect(page.locator("header .info")).toContainText(FIXTURE_NAME);

  const [download] = await Promise.all([
    page.waitForEvent("download"),
    page.getByRole("button", { name: /download all as \.zip/i }).click(),
  ]);
  expect(download.suggestedFilename()).toBe("sample.zip");

  const stream = await download.createReadStream();
  const chunks: Buffer[] = [];
  for await (const c of stream) chunks.push(c as Buffer);
  const buf = Buffer.concat(chunks);
  // Zip local file header magic.
  expect(buf.slice(0, 4).toString("hex")).toBe("504b0304");
  // The zip should contain at least one of the fixture file paths.
  expect(buf.includes(Buffer.from("images/pixel.png"))).toBe(true);
});
